version: '3.9'

services:
  kanjiskip.node:
    image: registry.git.flo-lan.com/flo-lan/kanjiskip/${IMAGE_TAG}
    container_name: kanjiskip.node
    hostname: kanjiskip.node
    restart: unless-stopped
    ports:
      - 3004:3000
    environment:
      - NODE_ENV=production
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_SECURE=false
      - MAIL_FROM=contact@flo-lan.com
      - MAIL_USER=user
      - MAIL_PWD=password
